name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main] # only main, not every branch

# Prevent duplicate runs on same branch / PR (nice optimization)
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npm run check

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Test (coverage)
        run: npm run test:cov

      - name: Build
        run: npm run build

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node }}
          path: |
            coverage/**
            client/coverage/** # harmless if absent
